version: '3.5'

services:
  node_soup:
    container_name: mediasoupbackend
    build:
      context: ./      
    volumes:
       - ./example1:/usr/code
    ports:
      - "3001:3001"
      - "2000-2100:2000-2100"    